name = "trippy"
version = "0.14.0-dev"
author = "FujiApple <fujiapple852@gmail.com>"
long-about = "A network diagnostic tool"
arg-required-else-help = true

[args]
protocol = { short = "p", long = "protocol", value-parser = ["icmp", "udp", "tcp"] }
multi = { short = "m", long = "multi", num-args = 2, value-name = "ARG" }
